#!/usr/bin/python3
#  -- coding: utf-8 --

# Date: Tue 25 May 2021 14:14:38 CET
# Author: Margaux Fouque

# Description:
# SOLARIUS est un outil technique permettant de suivre la course du soleil
# tout au long de la journée.
# SOLARIUS doit rester à la même postion au cours du processus.

# Python Version 3.9
# ECAM - AAM 1


''' Contrôle d'un servomoteur avec un Raspberry Pi
Le programme demande à l'utilisateur d'entrer le rapport cyclique
(duty cycle) désiré, et le servomoteur se met à la position correspondante. '''


import RPi.GPIO as GPIO

servo_pin = 12  # équivalent de GPIO 18
     
GPIO.setmode(GPIO.BOARD)  # notation board plutôt que BCM

GPIO.setup(servo_pin, GPIO.OUT)  # pin configurée en sortie

pwm = GPIO.PWM(servo_pin, 50)  # pwm à une fréquence de 50 Hz

rapport = 7       # rapport cyclique initial de 7%

pwm.start(rapport)  

while True:
    print ("Rapport cyclique actuel: " , rapport)
    rapport = input ("Rapport cyclique desire:  ")
    pwm.ChangeDutyCycle(float(rapport))
